# Generated by Django 4.0.6 on 2022-07-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(default='', max_length=100)),
                ('quantity', models.IntegerField()),
                ('book_genre', models.CharField(default='', max_length=150)),
                ('is_best_seller', models.BooleanField(default=False)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
            ],
        ),
    ]
