# Generated by Django 4.0.6 on 2022-07-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_tutorial_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=1, null=True),
        ),
    ]
