# Generated by Django 4.0.6 on 2022-07-16 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_tutorial_ayz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='ayz',
        ),
    ]
