# Generated by Django 4.0.6 on 2022-07-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_remove_tutorial_ayz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
