# Generated by Django 4.0.6 on 2022-07-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='b_id',
        ),
        migrations.AlterField(
            model_name='members',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
